{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.service.name}}
  namespace: {{ .Values.backend.namespace}}
spec:
  selector:
    app: {{ .Values.backend.labels }}
  ports:
    - port: {{ .Values.backend.service.port }}
{{- end }}

#



{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.serviceName}}
  namespace: {{ .Values.postgres.namespace}}
spec:
  selector:
    app: {{ .Values.postgres.labels }}
  ports:
    - port: {{ .Values.postgres.service.port }}
{{- end }}
