namespace: 2-assignment

deployBackend: true
deployPostgres: false

replicaCount: 2


image:
  repository: vikasgirigoswami/last
  tag: latest

image2:
  repository: postgres:16

postgres:
  user: vikas
  password: admin123
  db: mydb
  storage: 1Gi
